// Single source of truth for how a seat looks in every state.
//
// The map and the legend both read from here, so a swatch can never drift
// from the seat it is supposed to explain. Everything resolves through
// @theme tokens — no literal greens/greys — so the cabin follows dark mode
// and the brand palette for free.

import type { CSSProperties } from 'react';

/** Prisma `SeatStatus` values plus the client-only "selected" state. */
export type SeatState = 'available' | 'selected' | 'reserved' | 'booked' | 'blocked';

interface SeatStateStyle {
  /** Surface + border — valid on both a seat button and a legend swatch. */
  body: string;
  /** Seat-number typography. `line-through` is the colour-blind-safe cue
   *  that a seat is gone; colour alone never carries that meaning. */
  label: string;
  /** Hover/press affordance — empty for anything the user cannot take. */
  interactive: string;
}

export const SEAT_STATE_STYLES: Record<SeatState, SeatStateStyle> = {
  available: {
    body: 'border-border bg-background',
    label: 'text-foreground',
    interactive:
      'cursor-pointer hover:border-primary hover:bg-primary/5 active:scale-95',
  },
  selected: {
    body: 'border-primary bg-primary',
    label: 'text-primary-foreground font-bold',
    interactive: 'cursor-pointer hover:bg-primary/90 active:scale-95',
  },
  reserved: {
    body: 'border-dashed border-muted-foreground/30 bg-muted',
    label: 'text-muted-foreground/70 line-through',
    interactive: '',
  },
  booked: {
    body: 'border-transparent bg-muted',
    label: 'text-muted-foreground/60 line-through',
    interactive: '',
  },
  blocked: {
    body: 'border-transparent bg-muted/60',
    label: 'text-muted-foreground/40 line-through',
    interactive: '',
  },
};

/** Diagonal hatch marking a seat the operator took out of service. Inline
 *  rather than an arbitrary utility — brand-new arbitrary values do not
 *  always get generated by the on-demand scanner in dev. */
export const BLOCKED_HATCH: CSSProperties = {
  backgroundImage:
    'repeating-linear-gradient(45deg, transparent, transparent 3px, var(--muted-foreground) 3px, var(--muted-foreground) 4px)',
  opacity: 0.25,
};

/** Legend rows, in the order a rider meets them. The picker filters this
 *  down to the states actually present in the cabin — explaining a colour
 *  that is nowhere on screen is noise, not help. */
export const SEAT_LEGEND_ORDER = [
  'available',
  'selected',
  'reserved',
  'booked',
  'blocked',
] as const satisfies readonly SeatState[];

/**
 * Where the aisle falls for a given cabin width. Sudanese intercity coaches
 * run 2+2; VIP runs 2+1 and minibuses 1+1, so the split is derived rather
 * than hardcoded to the old `columns === 4` assumption.
 */
export function aisleAfterColumn(columns: number): number {
  if (columns <= 2) return 1; // 1 | 1  minibus
  if (columns === 3) return 2; // 2 | 1  VIP
  if (columns <= 5) return 2; // 2 | 2  standard · 2 | 3  wide coach
  return 3; //                  3 | 3  double-deck lower saloon
}
