/**
 * Delete the synthetic demo listings, keeping every real home.
 *
 *   pnpm purge:synthetic                 # dry run — prints the full inventory
 *   pnpm purge:synthetic --backup-only   # write the backup file, delete nothing
 *   FORCE_SEED=1 pnpm purge:synthetic --apply
 *   FORCE_SEED=1 pnpm purge:synthetic --apply --hosts   # also drop emptied host slots
 *
 * ── What this is for ───────────────────────────────────────────────────────
 *
 * mkan.sd carried 583 listings: 74 scraped from Airbnb, 23 belonging to the
 * three real owners on 0001/0002/0003, and 486 generated by `seed-listings.ts`.
 * The generated ones were priced 39–133 SDG while the real ones sit at 12,500–
 * 261,500, so the same result grid showed a 1000× spread and no visitor could
 * read a price. They also carried one description sentence photocopied 485
 * times and 9 of the 41 amenity values.
 *
 * The catalogue is real homes now. This removes the rest.
 *
 * ── How the set is chosen ──────────────────────────────────────────────────
 *
 * By the generator's own signature, not by host or by date:
 *
 *   source IS NULL              — never touches an imported listing
 *   sourceListingId IS NULL     — belt and braces on the same point
 *   title matches ' in <X> Street, Building <N>'  — `seed-listings.ts:222`
 *     built every title that way, database row number included
 *   OR title IS NULL            — one abandoned empty draft (no price, no
 *     photos, no location, no bookings) left behind by the host wizard
 *
 * The 23 real-owner homes are Arabic-titled and match none of it. The script
 * refuses to run if the count is not what the last survey found, so a predicate
 * that starts catching real homes stops the run instead of eating them.
 *
 * ── Recovery ───────────────────────────────────────────────────────────────
 *
 * Everything deleted is written to `.data/purge-backup-<ISO>.json` first —
 * listings, locations, and every dependent row — so the set can be rebuilt.
 * The file lives beside the scrape captures and is gitignored for the same
 * reason: it contains account ids.
 */
import { config } from 'dotenv';
config({ override: true });

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

// Deferred until after env loads — the db-before-dotenv "DatabaseDoesNotExist"
// trap that `mkan-import.ts` documents.
let prisma: (typeof import('@/lib/db'))['db'];

const APPLY = process.argv.includes('--apply');
const BACKUP_ONLY = process.argv.includes('--backup-only');
const DROP_HOSTS = process.argv.includes('--hosts');
const argv = (n: string, d = ''): string => {
  const hit = process.argv.find((a) => a.startsWith(`--${n}=`));
  return hit ? hit.split('=').slice(1).join('=') : d;
};
/** The count the last survey found. A drift means the predicate moved. */
const EXPECT = parseInt(argv('expect', '486'), 10);
const TOLERANCE = parseInt(argv('tolerance', '0'), 10);
const OUT = argv('out', `scripts/crm/.data/purge-backup-${new Date().toISOString().replace(/[:.]/g, '-')}.json`);

/** `seed-listings.ts` built every title as "<adj> <type> in <district> Street, Building <idx>". */
const FORMULAIC = / in .* Street, Building \d+$/;

/** The guest accounts `seed-listings.ts` minted and `seed-conversations.ts` wrote threads from. */
const DEMO_GUEST_EMAILS = [1, 2, 3, 4, 5].map((n) => `traveler${n}@mkan.org`);

const isSynthetic = (l: { source: string | null; sourceListingId: string | null; title: string | null }): boolean =>
  l.source === null && l.sourceListingId === null && (l.title === null || FORMULAIC.test(l.title));

async function main(): Promise<void> {
  console.log('\n🧹 Purge synthetic listings\n');

  if (APPLY && process.env.NODE_ENV === 'production' && !process.env.FORCE_SEED) {
    throw new Error('Refusing to write to production without FORCE_SEED=1');
  }

  prisma = (await import('@/lib/db')).db;

  // ── 1. Classify every listing ────────────────────────────────────────────
  const all = await prisma.listing.findMany({
    select: { id: true, title: true, source: true, sourceListingId: true, locationId: true, hostId: true },
  });

  const doomed = all.filter(isSynthetic);
  const kept = all.filter((l) => !isSynthetic(l));
  const ids = doomed.map((l) => l.id);
  const locationIds = doomed.map((l) => l.locationId).filter((v): v is number => v != null);

  console.log(`   ${all.length} listings total`);
  console.log(`   ${doomed.length} synthetic — to delete`);
  console.log(`   ${kept.length} real — kept`);

  const keptBySource = kept.reduce<Record<string, number>>((acc, l) => {
    const k = l.source ?? 'owner-created';
    acc[k] = (acc[k] ?? 0) + 1;
    return acc;
  }, {});
  console.log(`     kept breakdown: ${Object.entries(keptBySource).map(([k, v]) => `${k} ${v}`).join(' · ')}`);

  if (Math.abs(doomed.length - EXPECT) > TOLERANCE) {
    throw new Error(
      `expected ${EXPECT} synthetic listings (±${TOLERANCE}), found ${doomed.length}. ` +
      `The predicate no longer describes the same set — check it before deleting anything, ` +
      `or pass --expect=${doomed.length} once you have.`
    );
  }

  // ── 2. Gather every dependent row ────────────────────────────────────────
  const listingWhere = { listingId: { in: ids } };
  const propertyWhere = { propertyId: { in: ids } };

  const conversations = await prisma.conversation.findMany({ where: listingWhere, select: { id: true } });
  const conversationIds = conversations.map((c) => c.id);
  const bookings = await prisma.booking.findMany({ where: listingWhere, select: { id: true } });
  const bookingIds = bookings.map((b) => b.id);
  const leases = await prisma.lease.findMany({ where: propertyWhere, select: { id: true } });
  const leaseIds = leases.map((l) => l.id);

  const [reviews, blockedDates, seasonalPricing, applications, messages, bookingPayments, payments] =
    await Promise.all([
      prisma.review.findMany({ where: listingWhere, select: { id: true } }),
      prisma.blockedDate.findMany({ where: listingWhere, select: { id: true } }),
      prisma.seasonalPricing.findMany({ where: listingWhere, select: { id: true } }),
      prisma.application.findMany({ where: propertyWhere, select: { id: true } }),
      prisma.message.findMany({ where: { conversationId: { in: conversationIds } }, select: { id: true } }),
      prisma.bookingPayment.findMany({ where: { bookingId: { in: bookingIds } }, select: { id: true } }),
      prisma.payment.findMany({ where: { leaseId: { in: leaseIds } }, select: { id: true } }),
    ]);

  console.log('\n   dependent rows:');
  const inventory: Array<[string, number]> = [
    ['Review', reviews.length],
    ['Booking', bookings.length],
    ['BookingPayment', bookingPayments.length],
    ['BlockedDate', blockedDates.length],
    ['SeasonalPricing', seasonalPricing.length],
    ['Conversation', conversations.length],
    ['Message', messages.length],
    ['Application', applications.length],
    ['Lease', leases.length],
    ['Payment', payments.length],
    ['Location', locationIds.length],
  ];
  for (const [name, n] of inventory) console.log(`     ${String(n).padStart(6)}  ${name}`);

  // ── 2b. Seeded inbox threads ─────────────────────────────────────────────
  // `seed-conversations.ts` wrote template host⇄guest threads from the five
  // `travelerN@mkan.org` demo guests. With the demo hosts gone those threads
  // sit in the three REAL owners' inboxes, so an owner logging in reads
  // fabricated guest messages. Scoped to the demo guest accounts by email —
  // never "all conversations", because a genuine inquiry from a real user is
  // indistinguishable from a seeded one by shape alone.
  const demoGuests = await prisma.user.findMany({
    where: { email: { in: DEMO_GUEST_EMAILS } },
    select: { id: true, email: true },
  });
  const demoGuestIds = demoGuests.map((u) => u.id);
  const seededConversations = await prisma.conversation.findMany({
    where: { guestId: { in: demoGuestIds } },
    select: { id: true },
  });
  const seededConversationIds = seededConversations.map((c) => c.id);
  const seededMessages = await prisma.message.count({
    where: { conversationId: { in: seededConversationIds } },
  });
  const otherConversations = await prisma.conversation.count({
    where: { guestId: { notIn: demoGuestIds.length ? demoGuestIds : ['-'] } },
  });
  console.log(`\n   ${seededConversations.length} seeded inbox threads (${seededMessages} messages) from ${demoGuests.length} demo guest accounts`);
  console.log(`     ${otherConversations} other conversations — left alone`);

  // ── 3. Host slots left with nothing ──────────────────────────────────────
  // The numbered slots 0001…0100 were pre-provisioned for owners the field team
  // had not signed up yet. 0001/0002/0003 went to real owners; the rest only
  // ever held generated listings. Never touch the three real ones — hard-coded,
  // not derived, because getting this wrong deletes a real person's account.
  const REAL_OWNERS = ['0001', '0002', '0003'];
  const slotHosts = await prisma.user.findMany({
    where: { role: 'MANAGER', email: { notIn: REAL_OWNERS } },
    select: { id: true, email: true, username: true, _count: { select: { listings: true } } },
  });
  const doomedByHost = new Set<string>();
  for (const l of doomed) doomedByHost.add(l.hostId);
  const keptCountByHost = kept.reduce<Record<string, number>>((acc, l) => {
    acc[l.hostId] = (acc[l.hostId] ?? 0) + 1;
    return acc;
  }, {});

  const emptiedHosts = slotHosts.filter(
    (u) => /^0\d{3}@mkan\.org$/.test(u.email ?? '') && doomedByHost.has(u.id) && !keptCountByHost[u.id]
  );
  console.log(`\n   ${emptiedHosts.length} numbered host slots left with zero listings`);
  console.log(`     ${emptiedHosts.map((u) => u.username ?? u.email).join(', ')}`);
  console.log(`     ${DROP_HOSTS ? 'will be deleted (--hosts)' : 'kept — pass --hosts to delete them too'}`);

  // ── 4. Backup ────────────────────────────────────────────────────────────
  const backup = {
    purgedAt: new Date().toISOString(),
    predicate: 'source IS NULL AND sourceListingId IS NULL AND (formulaic title OR title IS NULL)',
    counts: Object.fromEntries([...inventory, ['Listing', doomed.length]]),
    listings: await prisma.listing.findMany({ where: { id: { in: ids } } }),
    locations: await prisma.location.findMany({ where: { id: { in: locationIds } } }),
    reviews: await prisma.review.findMany({ where: listingWhere }),
    bookings: await prisma.booking.findMany({ where: listingWhere }),
    blockedDates: await prisma.blockedDate.findMany({ where: listingWhere }),
    seasonalPricing: await prisma.seasonalPricing.findMany({ where: listingWhere }),
    conversations: await prisma.conversation.findMany({ where: listingWhere }),
    messages: await prisma.message.findMany({ where: { conversationId: { in: conversationIds } } }),
    applications: await prisma.application.findMany({ where: propertyWhere }),
    leases: await prisma.lease.findMany({ where: propertyWhere }),
    hosts: DROP_HOSTS ? emptiedHosts : [],
    seededConversations: await prisma.conversation.findMany({ where: { guestId: { in: demoGuestIds } } }),
    seededMessages: await prisma.message.findMany({ where: { conversationId: { in: seededConversationIds } } }),
    demoGuests,
  };
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, JSON.stringify(backup, null, 2));
  console.log(`\n   backup → ${OUT}`);

  if (BACKUP_ONLY) { console.log('\n--backup-only — nothing deleted.\n'); return; }
  if (!APPLY) { console.log('\nDRY RUN — re-run with --apply (and FORCE_SEED=1) to delete.\n'); return; }

  // ── 5. Delete, parents last ──────────────────────────────────────────────
  // Application before Lease: an Application points at a Lease, not the other
  // way round. Payment before Lease for the same reason.
  await prisma.$transaction(async (tx) => {
    await tx.bookingPayment.deleteMany({ where: { bookingId: { in: bookingIds } } });
    await tx.review.deleteMany({ where: listingWhere });
    await tx.message.deleteMany({ where: { conversationId: { in: conversationIds } } });
    await tx.conversation.deleteMany({ where: listingWhere });
    // Seeded inbox threads, keyed on the demo guest rather than the listing —
    // they were written with `listingId: null`, so the sweep above misses them.
    await tx.message.deleteMany({ where: { conversationId: { in: seededConversationIds } } });
    await tx.conversation.deleteMany({ where: { id: { in: seededConversationIds } } });
    await tx.blockedDate.deleteMany({ where: listingWhere });
    await tx.seasonalPricing.deleteMany({ where: listingWhere });
    await tx.booking.deleteMany({ where: listingWhere });
    await tx.application.deleteMany({ where: propertyWhere });
    await tx.payment.deleteMany({ where: { leaseId: { in: leaseIds } } });
    await tx.lease.deleteMany({ where: propertyWhere });
    await tx.listing.deleteMany({ where: { id: { in: ids } } });
    await tx.location.deleteMany({ where: { id: { in: locationIds } } });
  }, { timeout: 120_000 });

  console.log(`\n✅ ${doomed.length} synthetic listings deleted`);

  if (DROP_HOSTS && emptiedHosts.length) {
    const hostIds = emptiedHosts.map((u) => u.id);
    await prisma.$transaction(async (tx) => {
      await tx.account.deleteMany({ where: { userId: { in: hostIds } } });
      await tx.session.deleteMany({ where: { userId: { in: hostIds } } });
      await tx.profile.deleteMany({ where: { userId: { in: hostIds } } });
      await tx.hostClaimToken.deleteMany({ where: { userId: { in: hostIds } } });
      await tx.user.deleteMany({ where: { id: { in: hostIds } } });
    }, { timeout: 120_000 });
    console.log(`✅ ${emptiedHosts.length} empty host slots deleted`);
  }

  const after = await prisma.listing.count();
  console.log(`\n   ${after} listings remain\n`);
}

main()
  .catch((e) => {
    console.error(`\n❌ ${(e as Error).message}\n`);
    process.exit(1);
  })
  .finally(async () => {
    if (prisma) await prisma.$disconnect();
  });
