-- Seed 7 team members into all 4 workspaces on the shared Twenty instance.
-- Idempotent: safe to re-run. Only inserts what is missing.
-- Password for all: 12345678  (bcrypt hash below; regenerate if you change it)
-- Role assigned: Member (promote to Admin later in Settings -> Members if needed)
--
-- Tables touched:
--   core."user"                      (global identity + passwordHash)
--   core."userWorkspace"             (membership: user <-> workspace)
--   <workspaceSchema>."workspaceMember" (per-workspace profile record)
--   core."roleTarget"               (assigns the Member role to the membership)

DO $$
DECLARE
  -- bcrypt hash of "12345678" (generated by the twenty-server bcrypt lib)
  pw text := '$2b$10$/lPha9fExrU9t1vONPIFaeKEWJ/jAVr6u9QJYKSB5mZsYA7kAKtIC';
  u          record;
  w          record;
  v_user_id  uuid;
  v_uw_id    uuid;
  v_created_user int := 0;
  v_created_uw   int := 0;
  v_created_wm   int := 0;
  v_created_rt   int := 0;
  v_has_member   boolean;
BEGIN
  -- team members: email, first name
  FOR u IN
    SELECT * FROM (VALUES
      ('abdout@databayt.org',  'Abdout'),
      ('aseel@databayt.org',   'Aseel'),
      ('sedon@databayt.org',   'Sedon'),
      ('moutaz@databayt.org',  'Moutaz'),
      ('ibrahim@databayt.org', 'Ibrahim'),
      ('samia@databayt.org',   'Samia'),
      ('moed@databayt.org',    'Moed')
    ) AS t(email, fname)
  LOOP
    -- 1) global user (identity + password)
    SELECT id INTO v_user_id FROM core."user" WHERE email = u.email;
    IF v_user_id IS NULL THEN
      INSERT INTO core."user"(email, "firstName", "lastName", "isEmailVerified", "passwordHash", locale)
      VALUES (u.email, u.fname, '', true, pw, 'en')
      RETURNING id INTO v_user_id;
      v_created_user := v_created_user + 1;
      RAISE NOTICE 'user created: %', u.email;
    END IF;

    -- workspaces: id, Member roleId, data schema, applicationId
    FOR w IN
      SELECT * FROM (VALUES
        ('44d2ae41-beba-4ab4-a2b3-ae04a888585b'::uuid, '16f5201f-76ab-408e-9b54-208fdf8e1c66'::uuid, 'workspace_42oj8oexbj9f2weuevgy4wq57', '135d2efb-c805-4186-a1b2-9939d977d8d2'::uuid), -- Mkan
        ('d8863cb2-abe1-481b-af60-cb2e1759e226'::uuid, '88b08702-af5b-4122-9b16-cdfd35da9c44'::uuid, 'workspace_cth4d39nbagwniv0w1fjcgtnq', '9121bab8-838d-437e-83a6-707cdb7f1cab'::uuid), -- Hogwarts
        ('48397dc7-3cdf-460c-89aa-b97b256114fe'::uuid, '13512a26-9bb3-468a-b8c6-2627958fa4d0'::uuid, 'workspace_49xiz3vugal08hzgbasq64s1q', 'fec7c8ab-03af-44cf-85b5-5ed2d1b8a4dd'::uuid), -- Sijillee
        ('c95c60c0-3228-430d-ba4b-eef6a91ff8bd'::uuid, '70f67d98-0eaf-4470-ab29-7b32ee320654'::uuid, 'workspace_bx5ohvep01fxpsl2fryy3ohbx', '6578bc86-a46e-418b-bb7b-0a3a425ac76e'::uuid)  -- Moallimee
      ) AS ws(workspace_id, role_id, schema_name, application_id)
    LOOP
      -- 2) membership row
      SELECT id INTO v_uw_id FROM core."userWorkspace"
        WHERE "userId" = v_user_id AND "workspaceId" = w.workspace_id AND "deletedAt" IS NULL;
      IF v_uw_id IS NULL THEN
        INSERT INTO core."userWorkspace"("userId", "workspaceId", locale)
        VALUES (v_user_id, w.workspace_id, 'en')
        RETURNING id INTO v_uw_id;
        v_created_uw := v_created_uw + 1;
      END IF;

      -- 3) per-workspace workspaceMember profile (dynamic schema)
      EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I."workspaceMember" WHERE "userId" = $1)', w.schema_name)
        INTO v_has_member USING v_user_id;
      IF NOT v_has_member THEN
        EXECUTE format(
          'INSERT INTO %I."workspaceMember"
             (id, "userId", "userEmail", "nameFirstName", "nameLastName", position, "colorScheme", locale)
           VALUES (gen_random_uuid(), $1, $2, $3, '''',
             (SELECT coalesce(max(position),0)+1 FROM %I."workspaceMember"), ''System'', ''en'')',
          w.schema_name, w.schema_name
        ) USING v_user_id, u.email, u.fname;
        v_created_wm := v_created_wm + 1;
      END IF;

      -- 4) assign Member role to the membership
      IF NOT EXISTS (
        SELECT 1 FROM core."roleTarget"
        WHERE "workspaceId" = w.workspace_id AND "userWorkspaceId" = v_uw_id
      ) THEN
        INSERT INTO core."roleTarget"
          ("workspaceId", "roleId", "userWorkspaceId", "universalIdentifier", "applicationId")
        VALUES (w.workspace_id, w.role_id, v_uw_id, gen_random_uuid(), w.application_id);
        v_created_rt := v_created_rt + 1;
      END IF;
    END LOOP;
  END LOOP;

  RAISE NOTICE '--- summary ---';
  RAISE NOTICE 'users created:            %', v_created_user;
  RAISE NOTICE 'memberships created:      %', v_created_uw;
  RAISE NOTICE 'workspaceMembers created: %', v_created_wm;
  RAISE NOTICE 'role assignments created: %', v_created_rt;
END $$;
